name: Trigger auto deployment for api-codexca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/api-codexca-AutoDeployTrigger-079e6f09-a027-40dc-9a7c-61b094fe9103.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APICODEXCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APICODEXCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APICODEXCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker Image to Azure Container Registry
        run: |
          IMAGE_TAG=llmcodexca.azurecr.io/api-codexca:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login llmcodexca.azurecr.io -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          docker push $IMAGE_TAG

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name api-codexca \
            --resource-group LLM-Codexca \
            --image llmcodexca.azurecr.io/api-codexca:${{ github.sha }}


